GET http://localhost:8080/racecar/api/race
Content-Type: application/json

### Generate Races ######################################

### RACE 1 - Generate
POST http://localhost:8080/racecar/api/race
Content-Type: application/json

{
  "name": "Sunday Cup",
  "location": "Roskilde",
  "date": "010722",
  "duration": 5,
  "carDTOs": []
}
### RACE 2 - Generate
POST http://localhost:8080/racecar/api/race
Content-Type: application/json

{
  "name": "Rookie Cup",
  "location": "Taastrup",
  "date": "300622",
  "duration": 3,
  "carDTOs": []
}

### ADD RELATION ######################################

### Add to Race 1: Car 1
PUT http://localhost:8080/racecar/api/race/add/1/1
Content-Type: application/json

### Add to Race 1: Car 2
PUT http://localhost:8080/racecar/api/race/add/1/2
Content-Type: application/json

### Add to Race 2: Car 1
PUT http://localhost:8080/racecar/api/race/add/2/1
Content-Type: application/json

### Add to Race 2: Car 2
PUT http://localhost:8080/racecar/api/race/add/2/2
Content-Type: application/json

### Remove RELATION ######################################

### Remove from Race 1: Car 1

DELETE http://localhost:8080/racecar/api/race/remove/1/1
Content-Type: application/json