GET http://localhost:8080/devops_starter_war_exploded/api/user/1
Content-Type: application/json


###
PUT http://localhost:8080/devops_starter_war_exploded/api/user/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Allan",
  "lastName": "Andersen",
  "email": "AA@mail.com",
  "renameMeDTOS": [
    {
      "id": 1,
      "str1": "First 1",
      "str2": "Last 1"
    }
  ]
}




###
PUT http://localhost:8080/devops_starter_war_exploded/api/user/addrenameme/1/2
Content-Type: application/json


###
DELETE http://localhost:8080/devops_starter_war_exploded/api/user/removerenameme/1/2
Content-Type: application/json